const kotobaData = [
    // ==================== BAB 1 (18 kata) ====================
    { hiragana: "わたし", meaning: "Saya" },
    { hiragana: "あなた", meaning: "Anda" },
    { hiragana: "あのひと", meaning: "Orang itu" },
    { hiragana: "せんせい", meaning: "Guru" },
    { hiragana: "きょうし", meaning: "Guru" },
    { hiragana: "がくせい", meaning: "Pelajar" },
    { hiragana: "かいしゃいん", meaning: "Karyawan perusahaan" },
    { hiragana: "しゃいん", meaning: "Karyawan" },
    { hiragana: "ぎんこういん", meaning: "Pegawai bank" },
    { hiragana: "いしゃ", meaning: "Dokter" },
    { hiragana: "けんきゅうしゃ", meaning: "Peneliti" },
    { hiragana: "だいがく", meaning: "Universitas" },
    { hiragana: "びょういん", meaning: "Rumah sakit" },
    { hiragana: "だれ", meaning: "Siapa" },
    { hiragana: "なんさい", meaning: "Umur berapa" },
    { hiragana: "はじめまして", meaning: "Salam kenal" },
    { hiragana: "しつれいします", meaning: "Permisi" },
    { hiragana: "おなまえは", meaning: "Nama Anda" },

    // ==================== BAB 2 (42 kata) ====================
    { hiragana: "これ", meaning: "Ini" },
    { hiragana: "それ", meaning: "Itu" },
    { hiragana: "あれ", meaning: "Itu (jauh)" },
    { hiragana: "この", meaning: "Ini (diikuti benda)" },
    { hiragana: "その", meaning: "Itu (diikuti benda)" },
    { hiragana: "あの", meaning: "Itu (jauh, +benda)" },
    { hiragana: "ほん", meaning: "Buku" },
    { hiragana: "じしょ", meaning: "Kamus" },
    { hiragana: "しんぶん", meaning: "Koran" },
    { hiragana: "ノート", meaning: "Buku catatan" },
    { hiragana: "てちょう", meaning: "Agenda" },
    { hiragana: "めいし", meaning: "Kartu nama" },
    { hiragana: "カード", meaning: "Kartu" },
    { hiragana: "えんぴつ", meaning: "Pensil" },
    { hiragana: "ボールペン", meaning: "Pulpen" },
    { hiragana: "シャープペンシル", meaning: "Pensil mekanik" },
    { hiragana: "かぎ", meaning: "Kunci" },
    { hiragana: "とけい", meaning: "Jam" },
    { hiragana: "かさ", meaning: "Payung" },
    { hiragana: "かばん", meaning: "Tas" },
    { hiragana: "テレビ", meaning: "TV" },
    { hiragana: "ラジオ", meaning: "Radio" },
    { hiragana: "カメラ", meaning: "Kamera" },
    { hiragana: "コンピューター", meaning: "Komputer" },
    { hiragana: "くるま", meaning: "Mobil" },
    { hiragana: "つくえ", meaning: "Meja" },
    { hiragana: "いす", meaning: "Kursi" },
    { hiragana: "チョコレート", meaning: "Cokelat" },
    { hiragana: "コーヒー", meaning: "Kopi" },
    { hiragana: "おみやげ", meaning: "Oleh-oleh" },
    { hiragana: "えいご", meaning: "Bahasa Inggris" },
    { hiragana: "にほんご", meaning: "Bahasa Jepang" },
    { hiragana: "なに", meaning: "Apa" },
    { hiragana: "そう", meaning: "Begitu" },
    { hiragana: "あのう", meaning: "Permisi (ragu)" },
    { hiragana: "えっ", meaning: "Apa?" },
    { hiragana: "どうぞ", meaning: "Silakan" },
    { hiragana: "どうもありがとうございました", meaning: "Terima kasih banyak" },
    { hiragana: "そうですか", meaning: "Benarkah?" },
    { hiragana: "ちがいます", meaning: "Salah/Bukan" },
    { hiragana: "あ", meaning: "Oh (kaget)" },
    { hiragana: "おせわになります", meaning: "Mohon bantuannya" },
    { hiragana: "こちらこそよろしく", meaning: "Sama-sama" },

    // ==================== BAB 3 (56 kata) ====================
    { hiragana: "ここ", meaning: "Di sini" },
    { hiragana: "そこ", meaning: "Di situ" },
    { hiragana: "あそこ", meaning: "Di sana" },
    { hiragana: "どこ", meaning: "Di mana" },
    { hiragana: "こちら", meaning: "Di sini (formal)" },
    { hiragana: "そちら", meaning: "Di situ (formal)" },
    { hiragana: "あちら", meaning: "Di sana (formal)" },
    { hiragana: "どちら", meaning: "Di mana (formal)" },
    { hiragana: "きょうしつ", meaning: "Ruang kelas" },
    { hiragana: "しょくどう", meaning: "Kantin" },
    { hiragana: "じむしょ", meaning: "Kantor" },
    { hiragana: "かいぎしつ", meaning: "Ruang rapat" },
    { hiragana: "うけつけ", meaning: "Resepsionis" },
    { hiragana: "ロビー", meaning: "Lobi" },
    { hiragana: "へや", meaning: "Kamar" },
    { hiragana: "トイレ", meaning: "Toilet" },
    { hiragana: "かいだん", meaning: "Tangga" },
    { hiragana: "エレベーター", meaning: "Lift" },
    { hiragana: "エスカレーター", meaning: "Eskalator" },
    { hiragana: "でんわ", meaning: "Telepon" },
    { hiragana: "おくに", meaning: "Negara" },
    { hiragana: "かいしゃ", meaning: "Perusahaan" },
    { hiragana: "うち", meaning: "Rumah" },
    { hiragana: "くつ", meaning: "Sepatu" },
    { hiragana: "ネクタイ", meaning: "Dasi" },
    { hiragana: "ワイン", meaning: "Anggur" },
    { hiragana: "うりば", meaning: "Tempat penjualan" },
    { hiragana: "ちか", meaning: "Bawah tanah" },
    { hiragana: "なんがい", meaning: "Lantai berapa" },
    { hiragana: "いくら", meaning: "Berapa (harga)" },
    { hiragana: "ひゃく", meaning: "Seratus" },
    { hiragana: "せん", meaning: "Seribu" },
    { hiragana: "まん", meaning: "Sepuluh ribu" },
    { hiragana: "すみません", meaning: "Maaf" },
    { hiragana: "どうも", meaning: "Terima kasih" },
    { hiragana: "いらっしゃいませ", meaning: "Selamat datang" },
    { hiragana: "みせてください", meaning: "Tolong tunjukkan" },
    { hiragana: "デパート", meaning: "Departemen store" },
    { hiragana: "おくじょう", meaning: "Atap" },
    { hiragana: "ゆうえんち", meaning: "Taman hiburan" },
    { hiragana: "りょうり", meaning: "Masakan" },
    { hiragana: "りょうりします", meaning: "Memasak" },
    { hiragana: "りんご", meaning: "Apel" },
    { hiragana: "きょうだい", meaning: "Saudara Kandung" },
    { hiragana: "おとうと", meaning: "Adik Laki-laki (Sendiri)" },
    { hiragana: "いもうと", meaning: "Adik Perempuan (Sendiri)" },
    { hiragana: "おとうとさん", meaning: "Adik Laki-laki (Orang-lain)" },
    { hiragana: "いもうとさん", meaning: "Adik Perempuan (Orang-lain)" },
    { hiragana: "あに", meaning: "Kakak Laki-laki (Sendiri)" },
    { hiragana: "おにいさん", meaning: "Kakak Laki-laki (Orang-lain)" },
    { hiragana: "あね", meaning: "Kakak Perempuan (Sendiri)" },
    { hiragana: "おねえさん", meaning: "Kakak Perempuan (Orang-lain)" },
    { hiragana: "ちち", meaning: "Ayah (Sendiri)" },
    { hiragana: "おとうさん", meaning: "Ayah (Orang-lain)" },
    { hiragana: "はは", meaning: "Ibu (Sendiri)" },
    { hiragana: "おかあさん", meaning: "Ibu (Orang-lain)" },
    { hiragana: "りょうしん", meaning: "Orang Tua (Kandung)" },

    // ==================== KATA KERJA DASAR (60 kata) ====================
    { hiragana: "おきます", meaning: "Bangun tidur" },
    { hiragana: "ねます", meaning: "Tidur" },
    { hiragana: "はたらきます", meaning: "Bekerja" },
    { hiragana: "やすみます", meaning: "Istirahat" },
    { hiragana: "べんきょうします", meaning: "Belajar" },
    { hiragana: "かいます", meaning: "Membeli" },
    { hiragana: "あさごはん", meaning: "Sarapan" },
    { hiragana: "ひるごはん", meaning: "Makan siang" },
    { hiragana: "ばんごはん", meaning: "Makan malam" },
    { hiragana: "みず", meaning: "Air" },
    { hiragana: "おちゃ", meaning: "Teh hijau" },
    { hiragana: "ぎゅうにゅう", meaning: "Susu sapi" },
    { hiragana: "きります", meaning: "Memotong" },
    { hiragana: "おくります", meaning: "Mengirim" },
    { hiragana: "あげます", meaning: "Memberi" },
    { hiragana: "もらいます", meaning: "Menerima" },
    { hiragana: "かします", meaning: "Meminjamkan" },
    { hiragana: "かります", meaning: "Meminjam" },
    { hiragana: "おしえます", meaning: "Mengajar" },
    { hiragana: "ならいます", meaning: "Belajar (dari guru)" },
    { hiragana: "あそびます", meaning: "Bermain" },
    { hiragana: "およぎます", meaning: "Berenang" },
    { hiragana: "いそぎます", meaning: "Bergegas" },
    { hiragana: "まちます", meaning: "Menunggu" },
    { hiragana: "つくります", meaning: "Membuat" },
    { hiragana: "うります", meaning: "Menjual" },
    { hiragana: "しります", meaning: "Mengetahui" },
    { hiragana: "のります", meaning: "Naik (kendaraan)" },
    { hiragana: "おります", meaning: "Turun" },
    { hiragana: "あびます", meaning: "Mandi" },
    { hiragana: "はいります", meaning: "Masuk" },
    { hiragana: "おぼえます", meaning: "Mengingat" },
    { hiragana: "わすれます", meaning: "Lupa" },
    { hiragana: "はらいます", meaning: "Membayar" },
    { hiragana: "かえします", meaning: "Mengembalikan" },
    { hiragana: "できます", meaning: "Bisa, dapat" },
    { hiragana: "あらいます", meaning: "Mencuci" },
    { hiragana: "うたいます", meaning: "Menyanyi" },
    { hiragana: "あつめます", meaning: "Mengumpulkan" },
    { hiragana: "のぼります", meaning: "Naik (mendaki)" },
    { hiragana: "とまります", meaning: "Menginap" },
    { hiragana: "いります", meaning: "Membutuhkan" },
    { hiragana: "しらべます", meaning: "Memeriksa" },
    { hiragana: "しゅうりします", meaning: "Memperbaiki" },
    { hiragana: "おもいます", meaning: "Berpikir" },
    { hiragana: "いいます", meaning: "Berkata" },
    { hiragana: "かちます", meaning: "Menang" },
    { hiragana: "まけます", meaning: "Kalah" },
    { hiragana: "きます", meaning: "Datang" },
    { hiragana: "します", meaning: "Melakukan" },
    { hiragana: "たべます", meaning: "Makan" },
    { hiragana: "のみます", meaning: "Minum" },
    { hiragana: "よみます", meaning: "Membaca" },
    { hiragana: "かきます", meaning: "Menulis" },
    { hiragana: "みます", meaning: "Melihat" },
    { hiragana: "いきます", meaning: "Pergi" },
    { hiragana: "かえります", meaning: "Pulang" },
    { hiragana: "とります", meaning: "Mengambil" },
    { hiragana: "はなします", meaning: "Berbicara" },
    { hiragana: "うまれます", meaning: "Lahir" },

    // ==================== KATA SIFAT (50 kata) ====================
    { hiragana: "きれいな", meaning: "Cantik, bersih" },
    { hiragana: "しずかな", meaning: "Sepi, tenang" },
    { hiragana: "ゆうめいな", meaning: "Terkenal" },
    { hiragana: "しんせつな", meaning: "Ramah" },
    { hiragana: "げんきな", meaning: "Sehat, ceria" },
    { hiragana: "おおきい", meaning: "Besar" },
    { hiragana: "ちいさい", meaning: "Kecil" },
    { hiragana: "あたらしい", meaning: "Baru" },
    { hiragana: "ふるい", meaning: "Lama" },
    { hiragana: "あつい", meaning: "Panas" },
    { hiragana: "さむい", meaning: "Dingin" },
    { hiragana: "わかります", meaning: "Mengerti" },
    { hiragana: "すきな", meaning: "Suka" },
    { hiragana: "きらいな", meaning: "Benci" },
    { hiragana: "じょうずな", meaning: "Hebat, mahir" },
    { hiragana: "へたな", meaning: "Tidak mahir" },
    { hiragana: "とおい", meaning: "Jauh" },
    { hiragana: "ちかい", meaning: "Dekat" },
    { hiragana: "はやい", meaning: "Cepat" },
    { hiragana: "おそい", meaning: "Lambat" },
    { hiragana: "あたたかい", meaning: "Hangat" },
    { hiragana: "すずしい", meaning: "Sejuk" },
    { hiragana: "ほしい", meaning: "Ingin" },
    { hiragana: "ひろい", meaning: "Luas" },
    { hiragana: "せまい", meaning: "Sempit" },
    { hiragana: "ねむい", meaning: "Mengantuk" },
    { hiragana: "つよい", meaning: "Kuat" },
    { hiragana: "よわい", meaning: "Lemah" },
    { hiragana: "たかい", meaning: "Tinggi, mahal" },
    { hiragana: "ひくい", meaning: "Rendah" },
    { hiragana: "やすい", meaning: "Murah" },
    { hiragana: "おいしい", meaning: "Enak" },
    { hiragana: "まずい", meaning: "Tidak enak" },
    { hiragana: "あまい", meaning: "Manis" },
    { hiragana: "からい", meaning: "Pedas" },
    { hiragana: "しおからい", meaning: "Asin" },
    { hiragana: "すっぱい", meaning: "Asam" },
    { hiragana: "にがい", meaning: "Pahit" },
    { hiragana: "むずかしい", meaning: "Sulit" },
    { hiragana: "やさしい", meaning: "Mudah" },
    { hiragana: "おもしろい", meaning: "Menarik" },
    { hiragana: "つまらない", meaning: "Membosankan" },
    { hiragana: "こわい", meaning: "Menakutkan" },
    { hiragana: "うれしい", meaning: "Senang" },
    { hiragana: "さびしい", meaning: "Kesepian" },
    { hiragana: "つらい", meaning: "Menyakitkan" },
    { hiragana: "かっこいい", meaning: "Keren" },
    { hiragana: "かわいい", meaning: "Imut" },
    { hiragana: "わかい", meaning: "Muda" },
    { hiragana: "としより", meaning: "Lanjut usia" },

    // ==================== KATA BENDA LANJUTAN (40 kata) ====================
    { hiragana: "りょこう", meaning: "Wisata" },
    { hiragana: "おんがく", meaning: "Musik" },
    { hiragana: "いぬ", meaning: "Anjing" },
    { hiragana: "ねこ", meaning: "Kucing" },
    { hiragana: "うえ", meaning: "Atas" },
    { hiragana: "した", meaning: "Bawah" },
    { hiragana: "まえ", meaning: "Depan" },
    { hiragana: "うしろ", meaning: "Belakang" },
    { hiragana: "かかります", meaning: "Memerlukan waktu" },
    { hiragana: "きって", meaning: "Perangko" },
    { hiragana: "ぜんぶで", meaning: "Semuanya" },
    { hiragana: "レストラン", meaning: "Restoran" },
    { hiragana: "めがね", meaning: "Kacamata" },
    { hiragana: "こどものふく", meaning: "Pakaian anak" },
    { hiragana: "おもちゃ", meaning: "Mainan" },
    { hiragana: "ぶんぼうぐ", meaning: "Alat tulis" },
    { hiragana: "かぐ", meaning: "Perabotan" },
    { hiragana: "しょうき", meaning: "Peralatan makan" },
    { hiragana: "でんきせいひん", meaning: "Elektronik" },
    { hiragana: "しんしふく", meaning: "Pakaian pria" },
    { hiragana: "ふじんふく", meaning: "Pakaian wanita" },
    { hiragana: "けしょうひん", meaning: "Kosmetik" },
    { hiragana: "しょくひん", meaning: "Makanan" },
    { hiragana: "ちゅうしゃじょう", meaning: "Tempat parkir" },
    { hiragana: "エアコン", meaning: "AC" },
    { hiragana: "れいぞうこ", meaning: "Kulkas" },
    { hiragana: "でんしレンジ", meaning: "Microwave" },
    { hiragana: "せんたくき", meaning: "Mesin cuci" },
    { hiragana: "そうじき", meaning: "Vacuum cleaner" },
    { hiragana: "がっこう", meaning: "Sekolah" },
    { hiragana: "こうえん", meaning: "Taman" },
    { hiragana: "えき", meaning: "Stasiun" },
    { hiragana: "びじゅつかん", meaning: "Museum seni" },
    { hiragana: "としょかん", meaning: "Perpustakaan" },
    { hiragana: "ゆうびんきょく", meaning: "Kantor pos" },
    { hiragana: "けいさつしょ", meaning: "Kantor polisi" },
    { hiragana: "きっさてん", meaning: "Kafe" },
    { hiragana: "コンビニ", meaning: "Convenience store" },
    { hiragana: "スーパー", meaning: "Supermarket" },
    { hiragana: "ホテル", meaning: "Hotel" },

    // ==================== KATA KERJA LANJUTAN (30 kata) ====================
    { hiragana: "まわします", meaning: "Memutar" },
    { hiragana: "まがります", meaning: "Belok" },
    { hiragana: "くれます", meaning: "Diberikan (kepada saya)" },
    { hiragana: "なおします", meaning: "Mengoreksi" },
    { hiragana: "かんがえます", meaning: "Berpikir" },
    { hiragana: "つきます", meaning: "Sampai" },
    { hiragana: "たります", meaning: "Cukup" },
    { hiragana: "あけます", meaning: "Membuka" },
    { hiragana: "しめます", meaning: "Menutup" },
    { hiragana: "やっきょく", meaning: "Apotek" },
    { hiragana: "はなや", meaning: "Toko bunga" },
    { hiragana: "ほんや", meaning: "Toko buku" },
    { hiragana: "くだものや", meaning: "Toko buah" },
    { hiragana: "にくや", meaning: "Toko daging" },
    { hiragana: "パンや", meaning: "Toko roti" },
    { hiragana: "こうてい", meaning: "Lapangan sekolah" },
    { hiragana: "としょしつ", meaning: "Ruang perpustakaan" },
    { hiragana: "りかしつ", meaning: "Ruang IPA" },
    { hiragana: "おんがくしつ", meaning: "Ruang musik" },
    { hiragana: "たいいくかん", meaning: "Gedung olahraga" },
    { hiragana: "プール", meaning: "Kolam renang" },
    { hiragana: "いえ", meaning: "Rumah" },
    { hiragana: "まど", meaning: "Jendela" },
    { hiragana: "ドア", meaning: "Pintu" },
    { hiragana: "ゆか", meaning: "Lantai" },
    { hiragana: "てんじょう", meaning: "Langit-langit" },
    { hiragana: "かべ", meaning: "Dinding" },
    { hiragana: "だんぼう", meaning: "Pemanas ruangan" },
    { hiragana: "れいぼう", meaning: "Pendingin ruangan" },
    { hiragana: "でんき", meaning: "Listrik" },

    // ==================== KATA KETERANGAN (20 kata) ====================
    { hiragana: "よく", meaning: "Sering" },
    { hiragana: "ときどき", meaning: "Kadang-kadang" },
    { hiragana: "あまり", meaning: "Tidak terlalu" },
    { hiragana: "ぜんぜん", meaning: "Sama sekali tidak" },
    { hiragana: "とても", meaning: "Sangat" },
    { hiragana: "すこし", meaning: "Sedikit" },
    { hiragana: "たくさん", meaning: "Banyak" },
    { hiragana: "いつも", meaning: "Selalu" },
    { hiragana: "たいてい", meaning: "Biasanya" },
    { hiragana: "まいにち", meaning: "Setiap hari" },
    { hiragana: "まいあさ", meaning: "Setiap pagi" },
    { hiragana: "まいばん", meaning: "Setiap malam" },
    { hiragana: "きのう", meaning: "Kemarin" },
    { hiragana: "きょう", meaning: "Hari ini" },
    { hiragana: "あした", meaning: "Besok" },
    { hiragana: "あさって", meaning: "Lusa" },
    { hiragana: "おととい", meaning: "Kemarin lusa" },
    { hiragana: "いつ", meaning: "Kapan" },
    { hiragana: "なぜ", meaning: "Mengapa" },
    { hiragana: "どう", meaning: "Bagaimana" },

    // ==================== KATA TANYA & KATA BENDA (20 kata) ====================
    { hiragana: "いくつ", meaning: "Berapa (umur/jumlah)" },
    { hiragana: "どれ", meaning: "Yang mana" },
    { hiragana: "どの", meaning: "Yang mana (diikuti kata)" },
    { hiragana: "どっち", meaning: "Mana (2 pilihan)" },
    { hiragana: "ガス", meaning: "Gas" },
    { hiragana: "すいどう", meaning: "Air ledeng" },
    { hiragana: "ふろ", meaning: "Bak mandi" },
    { hiragana: "だいどころ", meaning: "Dapur" },
    { hiragana: "あかい", meaning: "Merah" },
    { hiragana: "あおい", meaning: "Biru" },
    { hiragana: "しろい", meaning: "Putih" },
    { hiragana: "くろい", meaning: "Hitam" },
    { hiragana: "きいろい", meaning: "Kuning" },
    { hiragana: "みどり", meaning: "Hijau" },
    { hiragana: "むらさき", meaning: "Ungu" },
    { hiragana: "ピンク", meaning: "Merah muda" },
    { hiragana: "オレンジ", meaning: "Oranye" },
    { hiragana: "ちゃいろ", meaning: "Cokelat" },
    { hiragana: "はいいろ", meaning: "Abu-abu" },

    // ==================== MAKANAN & MINUMAN (40 kata) ====================
    { hiragana: "ごはん", meaning: "Nasi" },
    { hiragana: "パン", meaning: "Roti" },
    { hiragana: "めん", meaning: "Mi" },
    { hiragana: "やさい", meaning: "Sayuran" },
    { hiragana: "くだもの", meaning: "Buah" },
    { hiragana: "にく", meaning: "Daging" },
    { hiragana: "さかな", meaning: "Ikan" },
    { hiragana: "たまご", meaning: "Telur" },
    { hiragana: "チーズ", meaning: "Keju" },
    { hiragana: "バター", meaning: "Mentega" },
    { hiragana: "サラダ", meaning: "Salad" },
    { hiragana: "スープ", meaning: "Sup" },
    { hiragana: "カレー", meaning: "Kari" },
    { hiragana: "ハンバーガー", meaning: "Hamburger" },
    { hiragana: "ピザ", meaning: "Pizza" },
    { hiragana: "アイスクリーム", meaning: "Es krim" },
    { hiragana: "ケーキ", meaning: "Kue" },
    { hiragana: "ジュース", meaning: "Jus" },
    { hiragana: "ビール", meaning: "Bir" },
    { hiragana: "みそしる", meaning: "Sup miso" },
    { hiragana: "すし", meaning: "Sushi" },
    { hiragana: "てんぷら", meaning: "Tempura" },
    { hiragana: "やきとり", meaning: "Yakitori" },
    { hiragana: "おでん", meaning: "Oden" },
    { hiragana: "そば", meaning: "Soba" },
    { hiragana: "うどん", meaning: "Udon" },
    { hiragana: "ラーメン", meaning: "Ramen" },
    { hiragana: "おにぎり", meaning: "Onigiri" },
    { hiragana: "もち", meaning: "Mochi" },
    { hiragana: "だんご", meaning: "Dango" },
    { hiragana: "たこやき", meaning: "Takoyaki" },
    { hiragana: "おこのみやき", meaning: "Okonomiyaki" },
    { hiragana: "にぎりずし", meaning: "Nigiri sushi" },
    { hiragana: "まきずし", meaning: "Maki sushi" },
    { hiragana: "てんぷら", meaning: "Tempura" },
    { hiragana: "かつどん", meaning: "Katsudon" },
    { hiragana: "ぎょうざ", meaning: "Gyoza" },
    { hiragana: "しゅうまい", meaning: "Shumai" },
    { hiragana: "やきそば", meaning: "Yakisoba" },

    // ==================== KELUARGA (20 kata) ====================
    { hiragana: "かぞく", meaning: "Keluarga" },
    { hiragana: "ふうふ", meaning: "Suami istri" },
    { hiragana: "しゅじん", meaning: "Suami" },
    { hiragana: "かない", meaning: "Istri" },
    { hiragana: "こども", meaning: "Anak" },
    { hiragana: "むすこ", meaning: "Anak laki-laki" },
    { hiragana: "むすめ", meaning: "Anak perempuan" },
    { hiragana: "まご", meaning: "Cucu" },
    { hiragana: "おじ", meaning: "Paman" },
    { hiragana: "おば", meaning: "Bibi" },
    { hiragana: "いとこ", meaning: "Sepupu" },
    { hiragana: "おじいさん", meaning: "Kakek" },
    { hiragana: "おばあさん", meaning: "Nenek" },
    { hiragana: "おとこ", meaning: "Pria" },
    { hiragana: "おんな", meaning: "Wanita" },
    { hiragana: "おとな", meaning: "Dewasa" },
    { hiragana: "にほんじん", meaning: "Orang Jepang" },
    { hiragana: "がいこくじん", meaning: "Orang asing" },
    { hiragana: "ともだち", meaning: "Teman" },
    { hiragana: "ゆうじん", meaning: "Sahabat" },

    // ==================== PAKAIAN (20 kata) ====================
    { hiragana: "ふく", meaning: "Pakaian" },
    { hiragana: "シャツ", meaning: "Kemeja" },
    { hiragana: "ズボン", meaning: "Celana" },
    { hiragana: "スカート", meaning: "Rok" },
    { hiragana: "ジャケット", meaning: "Jaket" },
    { hiragana: "コート", meaning: "Mantel" },
    { hiragana: "セーター", meaning: "Sweater" },
    { hiragana: "Tシャツ", meaning: "Kaos" },
    { hiragana: "くつした", meaning: "Kaus kaki" },
    { hiragana: "ぼうし", meaning: "Topi" },
    { hiragana: "マフラー", meaning: "Syal" },
    { hiragana: "ベルト", meaning: "Sabuk" },
    { hiragana: "てぶくろ", meaning: "Sarung tangan" },
    { hiragana: "スーツ", meaning: "Setelan jas" },
    { hiragana: "ゆかた", meaning: "Yukata" },
    { hiragana: "きもの", meaning: "Kimono" },
    { hiragana: "はっぴ", meaning: "Happi" },
    { hiragana: "サンダル", meaning: "Sandal" },
    { hiragana: "ブーツ", meaning: "Boots" },

    // ==================== KESEHATAN & TUBUH (25 kata) ====================
    { hiragana: "からだ", meaning: "Tubuh" },
    { hiragana: "あたま", meaning: "Kepala" },
    { hiragana: "かお", meaning: "Wajah" },
    { hiragana: "くち", meaning: "Mulut" },
    { hiragana: "は", meaning: "Gigi" },
    { hiragana: "みみ", meaning: "Telinga" },
    { hiragana: "め", meaning: "Mata" },
    { hiragana: "はな", meaning: "Hidung" },
    { hiragana: "て", meaning: "Tangan" },
    { hiragana: "あし", meaning: "Kaki" },
    { hiragana: "くすり", meaning: "Obat" },
    { hiragana: "ねつ", meaning: "Demam" },
    { hiragana: "いたい", meaning: "Sakit" },
    { hiragana: "かぜ", meaning: "Pilek" },
    { hiragana: "びょうき", meaning: "Penyakit" },
    { hiragana: "けが", meaning: "Luka" },
    { hiragana: "びょういん", meaning: "Rumah sakit" },
    { hiragana: "しんぞう", meaning: "Jantung" },
    { hiragana: "はい", meaning: "Paru-paru" },
    { hiragana: "い", meaning: "Perut" },
    { hiragana: "せぼね", meaning: "Tulang punggung" },
    { hiragana: "ほね", meaning: "Tulang" },
    { hiragana: "かわ", meaning: "Kulit" },
    { hiragana: "ち", meaning: "Darah" },

    // ==================== WAKTU (25 kata) ====================
    { hiragana: "じかん", meaning: "Waktu" },
    { hiragana: "とき", meaning: "Saat" },
    { hiragana: "じ", meaning: "Jam" },
    { hiragana: "ふん", meaning: "Menit" },
    { hiragana: "びょう", meaning: "Detik" },
    { hiragana: "にちようび", meaning: "Minggu" },
    { hiragana: "げつようび", meaning: "Senin" },
    { hiragana: "かようび", meaning: "Selasa" },
    { hiragana: "すいようび", meaning: "Rabu" },
    { hiragana: "もくようび", meaning: "Kamis" },
    { hiragana: "きんようび", meaning: "Jumat" },
    { hiragana: "どようび", meaning: "Sabtu" },
    { hiragana: "つき", meaning: "Bulan" },
    { hiragana: "とし", meaning: "Tahun" },
    { hiragana: "あさ", meaning: "Pagi" },
    { hiragana: "ひる", meaning: "Siang" },
    { hiragana: "ばん", meaning: "Malam" },
    { hiragana: "よる", meaning: "Malam hari" },
    { hiragana: "ゆうがた", meaning: "Sore" },
    { hiragana: "はる", meaning: "Musim semi" },
    { hiragana: "なつ", meaning: "Musim panas" },
    { hiragana: "あき", meaning: "Musim gugur" },
    { hiragana: "ふゆ", meaning: "Musim dingin" },
    { hiragana: "しょうらい", meaning: "Masa depan" },

    // ==================== KANTOR & BISNIS (25 kata) ====================
    { hiragana: "しごと", meaning: "Pekerjaan" },
    { hiragana: "しゅっちょう", meaning: "Perjalanan dinas" },
    { hiragana: "かいぎ", meaning: "Rapat" },
    { hiragana: "しんしゃ", meaning: "Perusahaan" },
    { hiragana: "きゃく", meaning: "Tamu" },
    { hiragana: "ファックス", meaning: "Fax" },
    { hiragana: "メール", meaning: "Email" },
    { hiragana: "パソコン", meaning: "Komputer" },
    { hiragana: "けいたい", meaning: "Ponsel" },
    { hiragana: "スマホ", meaning: "Smartphone" },
    { hiragana: "インターネット", meaning: "Internet" },
    { hiragana: "おかね", meaning: "Uang" },
    { hiragana: "ぎんこう", meaning: "Bank" },
    { hiragana: "しょくぎょう", meaning: "Profesi" },
    { hiragana: "べんごし", meaning: "Pengacara" },
    { hiragana: "けいかん", meaning: "Polisi" },
    { hiragana: "しょうぼうし", meaning: "Pemadam kebakaran" },
    { hiragana: "みせ", meaning: "Toko" },
    { hiragana: "かく", meaning: "Lantai" },
    { hiragana: "いっかい", meaning: "Lantai 1" },
    { hiragana: "にかい", meaning: "Lantai 2" },
    { hiragana: "さんかい", meaning: "Lantai 3" },
    { hiragana: "よんかい", meaning: "Lantai 4" },
    { hiragana: "ごかい", meaning: "Lantai 5" },
    { hiragana: "ろっかい", meaning: "Lantai 6" },

    // ==================== OLAHRAGA (25 kata) ====================
    { hiragana: "うんどう", meaning: "Olahraga" },
    { hiragana: "テニス", meaning: "Tenis" },
    { hiragana: "サッカー", meaning: "Sepak bola" },
    { hiragana: "バスケットボール", meaning: "Basket" },
    { hiragana: "やきゅう", meaning: "Bisbol" },
    { hiragana: "すいえい", meaning: "Renang" },
    { hiragana: "スキー", meaning: "Ski" },
    { hiragana: "スケート", meaning: "Skate" },
    { hiragana: "バレーボール", meaning: "Voli" },
    { hiragana: "バドミントン", meaning: "Bulu tangkis" },
    { hiragana: "ゴルフ", meaning: "Golf" },
    { hiragana: "ボウリング", meaning: "Bowling" },
    { hiragana: "けんどう", meaning: "Kendo" },
    { hiragana: "じゅうどう", meaning: "Judo" },
    { hiragana: "からて", meaning: "Karate" },
    { hiragana: "すもう", meaning: "Sumo" },
    { hiragana: "マラソン", meaning: "Maraton" },
    { hiragana: "ジョギング", meaning: "Jogging" },
    { hiragana: "サイクリング", meaning: "Bersepeda" },
    { hiragana: "やまのぼり", meaning: "Mendaki gunung" },
    { hiragana: "キャンプ", meaning: "Berkemah" },
    { hiragana: "はんちょう", meaning: "Panjat tebing" },

    // ==================== SENI & BUDAYA (25 kata) ====================
    { hiragana: "しゃしん", meaning: "Foto" },
    { hiragana: "え", meaning: "Gambar" },
    { hiragana: "ぶんか", meaning: "Budaya" },
    { hiragana: "れきし", meaning: "Sejarah" },
    { hiragana: "ちり", meaning: "Geografi" },
    { hiragana: "かがく", meaning: "Ilmu pengetahuan" },
    { hiragana: "すうがく", meaning: "Matematika" },
    { hiragana: "ちゅうごくご", meaning: "Bahasa Mandarin" },
    { hiragana: "かんこくご", meaning: "Bahasa Korea" },
    { hiragana: "ドイツご", meaning: "Bahasa Jerman" },
    { hiragana: "フランスご", meaning: "Bahasa Prancis" },
    { hiragana: "イタリアご", meaning: "Bahasa Italia" },
    { hiragana: "ロシアご", meaning: "Bahasa Rusia" },
    { hiragana: "スペインご", meaning: "Bahasa Spanyol" },
    { hiragana: "しょどう", meaning: "Kaligrafi" },
    { hiragana: "いけばな", meaning: "Merangkai bunga" },
    { hiragana: "さどう", meaning: "Upacara minum teh" },
    { hiragana: "にほん", meaning: "Jepang" },
    { hiragana: "ちゅうごく", meaning: "China" },
    { hiragana: "かんこく", meaning: "Korea" },
    { hiragana: "アメリカ", meaning: "Amerika" },
    { hiragana: "イギリス", meaning: "Inggris" },
    { hiragana: "フランス", meaning: "Prancis" },
    { hiragana: "イタリア", meaning: "Italia" },
    { hiragana: "ドイツ", meaning: "Jerman" },

    // ==================== ALAM & LINGKUNGAN (30 kata) ====================
    { hiragana: "あめ", meaning: "Hujan" },
    { hiragana: "ゆき", meaning: "Salju" },
    { hiragana: "はれ", meaning: "Cerah" },
    { hiragana: "くもり", meaning: "Berawan" },
    { hiragana: "かぜ", meaning: "Angin" },
    { hiragana: "かわ", meaning: "Sungai" },
    { hiragana: "うみ", meaning: "Laut" },
    { hiragana: "やま", meaning: "Gunung" },
    { hiragana: "はな", meaning: "Bunga" },
    { hiragana: "き", meaning: "Pohon" },
    { hiragana: "くさ", meaning: "Rumput" },
    { hiragana: "どうぶつ", meaning: "Hewan" },
    { hiragana: "とり", meaning: "Burung" },
    { hiragana: "むし", meaning: "Serangga" },
    { hiragana: "ほし", meaning: "Bintang" },
    { hiragana: "たいよう", meaning: "Matahari" },
    { hiragana: "そら", meaning: "Langit" },
    { hiragana: "くも", meaning: "Awan" },
    { hiragana: "かみなり", meaning: "Petir" },
    { hiragana: "にじ", meaning: "Pelangi" },
    { hiragana: "あおぞら", meaning: "Langit biru" },
    { hiragana: "つき", meaning: "Bulan" },
    { hiragana: "みずうみ", meaning: "Danau" },
    { hiragana: "もり", meaning: "Hutan" },
    { hiragana: "はやし", meaning: "Hutan kecil" },

    // ==================== PERJALANAN & TRANSPORTASI (30 kata) ====================
    { hiragana: "たび", meaning: "Perjalanan" },
    { hiragana: "てがみ", meaning: "Surat" },
    { hiragana: "はがき", meaning: "Kartu pos" },
    { hiragana: "きっぷ", meaning: "Tiket" },
    { hiragana: "パスポート", meaning: "Paspor" },
    { hiragana: "スーツケース", meaning: "Koper" },
    { hiragana: "りょかん", meaning: "Ryokan" },
    { hiragana: "おんせん", meaning: "Pemandian air panas" },
    { hiragana: "てら", meaning: "Kuil Buddha" },
    { hiragana: "じんじゃ", meaning: "Kuil Shinto" },
    { hiragana: "しろ", meaning: "Istana" },
    { hiragana: "はし", meaning: "Jembatan" },
    { hiragana: "みち", meaning: "Jalan" },
    { hiragana: "こうさてん", meaning: "Persimpangan" },
    { hiragana: "しんごう", meaning: "Lampu lalu lintas" },
    { hiragana: "じてんしゃ", meaning: "Sepeda" },
    { hiragana: "バイク", meaning: "Motor" },
    { hiragana: "バス", meaning: "Bus" },
    { hiragana: "タクシー", meaning: "Taksi" },
    { hiragana: "ひこうき", meaning: "Pesawat" },
    { hiragana: "ふね", meaning: "Kapal" },
    { hiragana: "でんしゃ", meaning: "Kereta listrik" },
    { hiragana: "しゅっぱつ", meaning: "Keberangkatan" },
    { hiragana: "とうちゃく", meaning: "Kedatangan" },
    { hiragana: "ちこく", meaning: "Telat" },
    { hiragana: "ゆめ", meaning: "Mimpi" },
    { hiragana: "きぼう", meaning: "Harapan" },
    { hiragana: "しあわせ", meaning: "Kebahagiaan" },
    { hiragana: "かなしみ", meaning: "Kesedihan" },
    { hiragana: "よろこび", meaning: "Kegembiraan" },

    // ==================== EMOSI & PERASAAN (20 kata) ====================
    { hiragana: "いかり", meaning: "Kemarahan" },
    { hiragana: "しんぱい", meaning: "Khawatir" },
    { hiragana: "きょうふ", meaning: "Ketakutan" },
    { hiragana: "ふあん", meaning: "Kecemasan" },
    { hiragana: "こうふん", meaning: "Kegembiraan" },
    { hiragana: "かんどう", meaning: "Terharu" },
    { hiragana: "いらいら", meaning: "Jengkel" },
    { hiragana: "がっかり", meaning: "Kecewa" },
    { hiragana: "ほっと", meaning: "Lega" },
    { hiragana: "うっとうしい", meaning: "Menyebalkan" },
    { hiragana: "なつかしい", meaning: "Rindu" },
    { hiragana: "いたい", meaning: "Sakit" },
    { hiragana: "かゆい", meaning: "Gatal" },
    { hiragana: "だるい", meaning: "Lesu" },
    { hiragana: "つかれた", meaning: "Lelah" },
    { hiragana: "ねむい", meaning: "Mengantuk" },
    { hiragana: "のどがかわいた", meaning: "Haus" },
    { hiragana: "おなかがすいた", meaning: "Lapar" },

    // ==================== TAMBAHAN TERAKHIR (40 kata) ====================
    { hiragana: "ざっし", meaning: "Majalah" },
    { hiragana: "まんが", meaning: "Komik" },
    { hiragana: "えいが", meaning: "Film" },
    { hiragana: "ドラマ", meaning: "Drama" },
    { hiragana: "アニメ", meaning: "Animasi" },
    { hiragana: "ゲーム", meaning: "Game" },
    { hiragana: "ロシア", meaning: "Rusia" },
    { hiragana: "オーストラリア", meaning: "Australia" },
    { hiragana: "インドネシア", meaning: "Indonesia" },
    { hiragana: "ゆびわ", meaning: "Cincin" },
    { hiragana: "ネックレス", meaning: "Kalung" },
    { hiragana: "アクセサリー", meaning: "Aksesoris" },
    { hiragana: "は", meaning: "Gigi" },
    { hiragana: "ほそい", meaning: "Tipis" },
    { hiragana: "ふとい", meaning: "Tebal" },
    { hiragana: "みじかい", meaning: "Pendek" },
    { hiragana: "ながい", meaning: "Panjang" },
    { hiragana: "おもい", meaning: "Berat" },
    { hiragana: "かるい", meaning: "Ringan" },
    { hiragana: "あぶない", meaning: "Berbahaya" },
    { hiragana: "たいへん", meaning: "Sulit/sangat" },
    { hiragana: "らく", meaning: "Mudah/nyaman" },
    { hiragana: "しあわせ", meaning: "Bahagia" },
    { hiragana: "ふこう", meaning: "Sial" },
    { hiragana: "うん", meaning: "Keberuntungan" },
    { hiragana: "あい", meaning: "Cinta" },
    { hiragana: "ゆうき", meaning: "Keberanian" },
    { hiragana: "かんしゃ", meaning: "Terima kasih" },
    { hiragana: "おれい", meaning: "Ucapan terima kasih" },
    { hiragana: "もうしわけ", meaning: "Permintaan maaf" },
    { hiragana: "こんにちは", meaning: "Selamat siang" },
    { hiragana: "こんばんは", meaning: "Selamat malam" },
    { hiragana: "おやすみなさい", meaning: "Selamat tidur" },
    { hiragana: "さようなら", meaning: "Selamat tinggal" },
    { hiragana: "いただきます", meaning: "Selamat makan" },
    { hiragana: "ごちそうさま", meaning: "Terima kasih atas makanannya" },
    { hiragana: "おだいじに", meaning: "Semoga cepat sembuh" },
    { hiragana: "おめでとう", meaning: "Selamat" },
    { hiragana: "よかった", meaning: "Syukurlah" },
    { hiragana: "ざんねん", meaning: "Sayang sekali" }
];

// DOM Elements
const searchInput = document.getElementById("searchInput");
const shuffleBtn = document.getElementById("shuffleBtn");
const kotobaList = document.getElementById("kotobaList");
const totalKata = document.getElementById("totalKata");
const tampilKata = document.getElementById("tampilKata");

// Tampilkan data awal
displayKotoba(kotobaData);

// Event listeners
searchInput.addEventListener("input", filterKotoba);
shuffleBtn.addEventListener("click", shuffleKotoba);

// Fungsi untuk menampilkan kosakata
function displayKotoba(data) {
    kotobaList.innerHTML = "";
    
    data.forEach((item, index) => {
        const row = document.createElement("tr");
        row.innerHTML = `
            <td>${index + 1}</td>
            <td>${item.hiragana}</td>
            <td>${item.meaning}</td>
        `;
        kotobaList.appendChild(row);
    });
    
    // Update statistik
    totalKata.textContent = kotobaData.length;
    tampilKata.textContent = data.length;
}

// Fungsi untuk memfilter kosakata
function filterKotoba() {
    const searchTerm = searchInput.value.toLowerCase().trim();
    
    if (searchTerm === '') {
        displayKotoba(kotobaData);
        return;
    }
    
    const filteredData = kotobaData.filter(item => 
        item.hiragana.toLowerCase().includes(searchTerm) || 
        item.meaning.toLowerCase().includes(searchTerm)
    );
    
    displayKotoba(filteredData);
}

// Fungsi untuk mengacak urutan kosakata
function shuffleKotoba() {
    const shuffledData = [...kotobaData];
    for (let i = shuffledData.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffledData[i], shuffledData[j]] = [shuffledData[j], shuffledData[i]];
    }
    displayKotoba(shuffledData);
}